import Providers from '@/components/Providers';
import PWARegister from '@/components/PWARegister';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Outfit, Ovo } from 'next/font/google';
import './globals.css';

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: ['400', '500', '600', '700'],
});

const ovo = Ovo({
  subsets: ['latin'],
  variable: '--font-ovo',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'SebaGriho',
  description: 'Generated by sebagriho development team',
  applicationName: 'SebaGriho',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'SebaGriho',
  },
  formatDetection: {
    telephone: false,
  },
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={`${outfit.variable} ${ovo.variable} h-full antialiased`}
    >
      <body className='flex min-h-full flex-col' suppressHydrationWarning>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <PWARegister />
            {children}
            <Toaster />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
